[2019-02-27 09:09:18,156: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 2.00 seconds...

[2019-02-27 09:09:20,160: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 4.00 seconds...

[2019-02-27 09:09:24,164: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 6.00 seconds...

[2019-02-27 09:09:30,172: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 8.00 seconds...

[2019-02-27 09:09:38,182: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 10.00 seconds...

[2019-02-27 09:09:48,194: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 12.00 seconds...

[2019-02-27 09:10:03,585: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 2.00 seconds...

[2019-02-27 09:10:05,589: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 4.00 seconds...

[2019-02-27 09:10:09,594: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 6.00 seconds...

[2019-02-27 09:10:15,602: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 8.00 seconds...

[2019-02-27 09:10:23,605: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 10.00 seconds...

[2019-02-27 09:10:33,617: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 12.00 seconds...

[2019-02-27 09:10:45,629: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 14.00 seconds...

[2019-02-27 09:10:59,643: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 16.00 seconds...

[2019-02-27 09:11:15,659: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 18.00 seconds...

[2019-02-27 09:11:33,673: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 20.00 seconds...

[2019-02-27 09:11:53,696: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 22.00 seconds...

[2019-02-27 09:12:15,720: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 24.00 seconds...

[2019-02-27 09:12:39,749: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 26.00 seconds...

[2019-02-27 09:13:05,774: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 28.00 seconds...

[2019-02-27 09:13:33,805: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 30.00 seconds...

[2019-02-27 09:14:03,835: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:14:35,871: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:15:07,884: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:15:39,917: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:16:11,951: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:16:43,981: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:17:16,003: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:17:48,033: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:18:20,066: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:18:52,099: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:19:24,132: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:19:56,157: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:20:28,175: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:21:00,195: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:21:32,236: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:22:04,264: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:22:36,290: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:23:08,324: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:23:40,354: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:24:12,380: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:24:44,410: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:25:16,437: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:25:48,468: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:26:20,498: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:26:52,523: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:27:24,555: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:27:56,588: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:28:28,620: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:29:00,649: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:29:32,679: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:30:04,708: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:30:36,742: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:31:08,772: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:31:40,807: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:32:12,837: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:32:44,871: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:33:16,905: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:33:48,939: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:34:20,971: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:34:53,008: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/8: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error..
Trying again in 32.00 seconds...

[2019-02-27 09:35:04,115: WARNING/MainProcess] Error in atexit._run_exitfuncs:
[2019-02-27 09:35:04,115: WARNING/MainProcess] Traceback (most recent call last):
[2019-02-27 09:35:04,116: WARNING/MainProcess] File "/usr/lib/python3.5/multiprocessing/util.py", line 254, in _run_finalizers
[2019-02-27 09:35:04,130: WARNING/MainProcess] finalizer()
[2019-02-27 09:35:04,131: WARNING/MainProcess] File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
[2019-02-27 09:35:04,131: WARNING/MainProcess] res = self._callback(*self._args, **self._kwargs)
[2019-02-27 09:35:04,131: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 1618, in _terminate_pool
[2019-02-27 09:35:04,148: WARNING/MainProcess] cls._help_stuff_finish(*help_stuff_finish_args)
[2019-02-27 09:35:04,148: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 1293, in _help_stuff_finish
[2019-02-27 09:35:04,161: WARNING/MainProcess] readable, _, again = _select(inqR, timeout=0.5)
[2019-02-27 09:35:04,161: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 180, in _select
[2019-02-27 09:35:04,161: WARNING/MainProcess] return poll(readers, writers, err, timeout)
[2019-02-27 09:35:04,161: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 136, in _select_imp
[2019-02-27 09:35:04,161: WARNING/MainProcess] events = poller.poll(timeout)
[2019-02-27 09:35:04,161: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/apps/worker.py", line 284, in _handle_request
[2019-02-27 09:35:04,175: WARNING/MainProcess] raise exc(exitcode)
[2019-02-27 09:35:04,175: WARNING/MainProcess] celery.exceptions
[2019-02-27 09:35:04,175: WARNING/MainProcess] .
[2019-02-27 09:35:04,175: WARNING/MainProcess] WorkerTerminate
[2019-02-27 09:35:04,175: WARNING/MainProcess] :
[2019-02-27 09:35:04,176: WARNING/MainProcess] 1
[2019-02-27 10:03:43,922: WARNING/MainProcess] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2019-02-27 10:08:12,577: WARNING/MainProcess] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2019-02-27 10:12:11,416: WARNING/MainProcess] Error in atexit._run_exitfuncs:
[2019-02-27 10:12:11,416: WARNING/MainProcess] Traceback (most recent call last):
[2019-02-27 10:12:11,417: WARNING/MainProcess] File "/usr/lib/python3.5/multiprocessing/util.py", line 254, in _run_finalizers
[2019-02-27 10:12:11,417: WARNING/MainProcess] finalizer()
[2019-02-27 10:12:11,417: WARNING/MainProcess] File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
[2019-02-27 10:12:11,417: WARNING/MainProcess] res = self._callback(*self._args, **self._kwargs)
[2019-02-27 10:12:11,417: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 1618, in _terminate_pool
[2019-02-27 10:12:11,418: WARNING/MainProcess] cls._help_stuff_finish(*help_stuff_finish_args)
[2019-02-27 10:12:11,418: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 1293, in _help_stuff_finish
[2019-02-27 10:12:11,418: WARNING/MainProcess] readable, _, again = _select(inqR, timeout=0.5)
[2019-02-27 10:12:11,418: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 180, in _select
[2019-02-27 10:12:11,419: WARNING/MainProcess] return poll(readers, writers, err, timeout)
[2019-02-27 10:12:11,419: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 136, in _select_imp
[2019-02-27 10:12:11,419: WARNING/MainProcess] events = poller.poll(timeout)
[2019-02-27 10:12:11,419: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/apps/worker.py", line 284, in _handle_request
[2019-02-27 10:12:11,419: WARNING/MainProcess] raise exc(exitcode)
[2019-02-27 10:12:11,419: WARNING/MainProcess] celery.exceptions
[2019-02-27 10:12:11,419: WARNING/MainProcess] .
[2019-02-27 10:12:11,420: WARNING/MainProcess] WorkerTerminate
[2019-02-27 10:12:11,420: WARNING/MainProcess] :
[2019-02-27 10:12:11,420: WARNING/MainProcess] 1
[2019-02-27 10:16:49,229: WARNING/MainProcess] Error in atexit._run_exitfuncs:
[2019-02-27 10:16:49,230: WARNING/MainProcess] Traceback (most recent call last):
[2019-02-27 10:16:49,230: WARNING/MainProcess] File "/usr/lib/python3.5/multiprocessing/util.py", line 254, in _run_finalizers
[2019-02-27 10:16:49,230: WARNING/MainProcess] finalizer()
[2019-02-27 10:16:49,230: WARNING/MainProcess] File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
[2019-02-27 10:16:49,230: WARNING/MainProcess] res = self._callback(*self._args, **self._kwargs)
[2019-02-27 10:16:49,230: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 1618, in _terminate_pool
[2019-02-27 10:16:49,231: WARNING/MainProcess] cls._help_stuff_finish(*help_stuff_finish_args)
[2019-02-27 10:16:49,231: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 1293, in _help_stuff_finish
[2019-02-27 10:16:49,231: WARNING/MainProcess] readable, _, again = _select(inqR, timeout=0.5)
[2019-02-27 10:16:49,231: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 180, in _select
[2019-02-27 10:16:49,232: WARNING/MainProcess] return poll(readers, writers, err, timeout)
[2019-02-27 10:16:49,232: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 136, in _select_imp
[2019-02-27 10:16:49,232: WARNING/MainProcess] events = poller.poll(timeout)
[2019-02-27 10:16:49,232: WARNING/MainProcess] File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/apps/worker.py", line 284, in _handle_request
[2019-02-27 10:16:49,232: WARNING/MainProcess] raise exc(exitcode)
[2019-02-27 10:16:49,232: WARNING/MainProcess] celery.exceptions
[2019-02-27 10:16:49,233: WARNING/MainProcess] .
[2019-02-27 10:16:49,233: WARNING/MainProcess] WorkerTerminate
[2019-02-27 10:16:49,233: WARNING/MainProcess] :
[2019-02-27 10:16:49,233: WARNING/MainProcess] 1
